### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by BabyDragonV2** [D4rkstalker/RW-Androids1.4#13]
its missing the about.xml file which just breaks the whole thing
also the lovers thing wasn't working
Edit: found out why the lovers mentality didnt work it was because of a gene called the unfeeling gene from another mod i had which removes mood and breaks lovers mentality for what ever reason.
edit 2: havent had any major issues if something goes horribly wrong its me messing with stat values but the missing about.xml file should be fixed

**Comment by D4rkstalker** [comment]
Try redownloading the mod from steam, the about.xml is present on my end
