### ISSUE TITLE
bug or feature...

### ISSUE THREAD

**Issue by BoopleShnoot** [D4rkstalker/RW-Androids1.4#14]
im not sure if this is a bug or a feature but an android starter clanist with and arcotech module has sucessfully carried a child to term 
![20230528135143_11](https://github.com/D4rkstalker/RW-Androids1.4/assets/109548201/33b836e8-d25c-4748-9fd8-760f2a52e9f6)
The other android starts i have all have 0% fertillity and this one has 100% is it a side effect of the arcotech module?

**Comment by D4rkstalker** [comment]
It's actually because of the age, I forgot to change the fertility curve so it's using the vanilla human one. It's fixed now
