### ISSUE TITLE
Can't change Head with Character Editor

### ISSUE THREAD

**Issue by Kazuhito9702** [D4rkstalker/RW-Androids1.4#5]
Can't change head type for any androids.
First, I was suspecting Character editor as the culprit, but other vanilla pawns have no problem changing head types and this is not also a HAR issue since many other HAR-oriented race(Anty, AOC, Kurin, Rabbie, Naki, Yuran, Miho, Paniel, etc. all tested)had no problem changing their head type so I think Android is the most suspicious.

Following is the red log after clicking things regarding head type change(randomize appearance, pressing dice in the head type box, pressing arrows next to the head type box, etc.)

**-----------------------------------------------------------------**

> Exception filling window for CharacterEditor.CEditor+EditorUI: System.ArgumentNullException: Value cannot be null.
> Parameter name: source
>   at System.Linq.Enumerable.ToHashSet[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0000d] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
>   at System.Linq.Enumerable.ToHashSet[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
>   at au.a (Verse.Pawn A_0, System.Boolean A_1) [0x00061] in <c8939592c4864ddbac4788573cf1c463>:0 
>   at au.a (Verse.Pawn A_0, System.Boolean A_1, System.Boolean A_2) [0x00010] in <c8939592c4864ddbac4788573cf1c463>:0 
>   at CharacterEditor.CEditor+EditorUI+BlockPerson.ax () [0x0000b] in <c8939592c4864ddbac4788573cf1c463>:0 
>   at bj.c (UnityEngine.Rect A_0, System.String A_1, System.Action A_2, System.String A_3) [0x00028] in <c8939592c4864ddbac4788573cf1c463>:0 
>   at bj.a (UnityEngine.Rect A_0, System.Action A_1, System.Action A_2, System.Action A_3, System.Action A_4, System.Action A_5, System.Action A_6, System.String A_7, System.String A_8, System.String A_9, System.String A_10, System.String A_11, UnityEngine.Color A_12, System.String A_13) [0x00031] in <c8939592c4864ddbac4788573cf1c463>:0 
>   at CharacterEditor.CEditor+EditorUI+BlockPerson.cf () [0x0010d] in <c8939592c4864ddbac4788573cf1c463>:0 
>   at CharacterEditor.CEditor+EditorUI+BlockPerson.a (CharacterEditor.CEditor+EditorUI+b A_0) [0x000c0] in <c8939592c4864ddbac4788573cf1c463>:0 
>   at CharacterEditor.CEditor+EditorUI.DoWindowContents (UnityEngine.Rect inRect) [0x00146] in <c8939592c4864ddbac4788573cf1c463>:0 
>   at Verse.Window.InnerWindowOnGUI (System.Int32 x) [0x001d3] in <8c412d4a16f94d4cb337e846f2dee469>:0 
> UnityEngine.StackTraceUtility:ExtractStackTrace ()
> (wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch3 (string)
> Verse.Window:InnerWindowOnGUI (int)
> UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)
>

**Comment by D4rkstalker** [comment]
Androids uses the default human graphics so that might be why.
Character editor probably saw "AlienRace" and looked for corresponding graphics defined under alien race when it should be looking under the vanilla path.
I don't think I can do anything on my end without breaking existing saves.
