### ISSUE TITLE
Andoid Maid outfits are undyeable and wearing a maid outfit breaks the dying interface

### ISSUE THREAD

**Issue by garnth** [D4rkstalker/RW-Androids1.4#8]
As the title says, any pawn wearing a maid outfit (either type) cannot use the dying section of the styling table.  This can easily be fixed in XML by editing the Apparel_Maid.xml file and adding ParentName="ApparelMakeableBase" to the ChjAndroidMaidoutfit def at the very top of the file.

**Comment by D4rkstalker** [comment]
Fixed now, thanks!
